name: manage-azure-policy-e581754b
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/DependencyAgentExtension_Linux_VM_Deploy_e886da65-61dc-4543-9c83-f3ec044059ed/**'
#      - .github/workflows/manage-azure-policy-e581754b.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_e581754b}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/DependencyAgentExtension_Linux_VM_Deploy_e886da65-61dc-4543-9c83-f3ec044059ed/**
